travis:
  secure:
    BINSTAR_TOKEN: bvF0sZSjr8iH+0V0H5n0mJ8Fh2Jw9LTjHt+l8OzXpNUXBn5/qKygvX3WhJQ0Io1HPI26QZBXi2qrl/a+N1lCWZitsINeLOMu4sBRL/i5zRj3Fi6XkpY7c4WpuzNfG6uRMYxRZa3IcjNbwDiuGHoG6DGNkZVCMMgZFhbYFkyZDtR85a1rWobbkmhPWNBHJZIo5aeHvZA8vyI7rA9w6aNMa+N2JkFtg4YuQNMnhkevDk+CZzMB9699XRPTJpTtusD1JXKvlxztk+yOkAaeQCNAEHMiZBNOh5mk1GhBTSIY2pI+vxAI08iFLXlPYmdTOEUqW+PVqFLi9zoFy7TYUgiaCuZmK54hbyHc37Nj9yyMaWrNMOcrHzIXjpsEMC++7XH8DuTiRiPg7enXLi7GyC/P9ELlt2zBWv5FkZ/vfAx6gSCaT02QeYd2o595ZM/b2igVciKRCEZ6eeXBbUCrtPSnqzWIx3imGQxUfhgIolx+LmvuAm6jziJO0xGJv9eU44KX2vwAFXIYL8dYPWblJN18SdepkQMd2X+62LSfaBbMCpZZK9GOiOccYkPxPmHPM0VDfLH/On+TytNKSIxTqMBujLaKwHaPX8JT3owLB8F4tkukeHewW6SVhisJYu1GsmyQ6MMJ+aYg1TLIRF11ajI6bLpEJyyPnqijU2NarYzH0mo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
